import smtplib
import os
import csv
import time  # <-- NEW: Imported for the delay
from email.message import EmailMessage
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Fetch SMTP configuration from .env
SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", 465))
SMTP_USER = os.getenv("SMTP_USER")
SMTP_PASS = os.getenv("SMTP_PASS")

# Define exact directory paths to avoid pathing issues
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CSV_PATH = os.path.join(BASE_DIR, 'student.csv')
OUTPUT_DIR = os.path.join(BASE_DIR, 'output')

def send_csv_emails():
    # 1. Check for credentials
    if not SMTP_USER or not SMTP_PASS:
        print("❌ Error: SMTP credentials not found. Please check your .env file.")
        return

    # 2. Check if CSV exists
    if not os.path.exists(CSV_PATH):
        print(f"❌ Error: Could not find {CSV_PATH}. Make sure the path is correct.")
        return

    print(f"Connecting to {SMTP_HOST} on port {SMTP_PORT}...")
    
    try:
        # Connect to the Gmail SMTP server using SSL
        with smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT) as server:
            # Log in using the app password
            server.login(SMTP_USER, SMTP_PASS)
            print("✅ Successfully logged into the email server.\n")

            # Open and read the CSV file
            with open(CSV_PATH, mode='r', encoding='utf-8') as file:
                reader = csv.DictReader(file)
                
                # Loop through each row in the CSV
                for row in reader:
                    name = row['name'].strip()
                    recipient_email = row['email'].strip()
                    workshop = row['workshopsession'].strip()
                    
                    # Clean up the workshop name for the email text
                    clean_workshop_name = workshop.replace("_", " ")

                    # Create the email message
                    msg = EmailMessage()
                    msg['Subject'] = f"E-Certificate of Participation: {clean_workshop_name}"
                    msg['From'] = SMTP_USER
                    msg['To'] = recipient_email
                    
                    # --- PROFESSIONAL EMAIL BODY ---
                    body = (
                        f"Dear {name},\n\n"
                        f"Thank you for your active participation in the {clean_workshop_name} hosted by the CamTech AI Lab.\n\n"
                        f"As a token of our appreciation, please find attached your official e-certificate of participation. We recommend saving this file for your personal records and portfolio.\n\n"
                        f"If you have any questions or require further assistance, please do not hesitate to contact us by replying directly to this email.\n\n"
                        f"We wish you all the best in your future endeavors!\n\n"
                        f"Sincerely,\n"
                        f"The CamTech AI Lab Team\n"
                        f"CamTech University"
                    )
                    msg.set_content(body)

                    # --- ATTACHMENT LOGIC ---
                    # Recreate the exact filename generated by main.py
                    safe_name = name.replace(" ", "_")
                    pdf_filename = f"{safe_name}_{workshop}_Certificate.pdf"
                    pdf_path = os.path.join(OUTPUT_DIR, pdf_filename)

                    # Check if the PDF exists before trying to attach it
                    if os.path.exists(pdf_path):
                        with open(pdf_path, 'rb') as pdf_file:
                            pdf_data = pdf_file.read()
                        
                        # Attach the PDF to the email
                        msg.add_attachment(
                            pdf_data, 
                            maintype='application', 
                            subtype='pdf', 
                            filename=pdf_filename
                        )
                        print(f"📎 Attached: {pdf_filename}")
                    else:
                        print(f"⚠️ Warning: PDF not found for {name} ({pdf_filename}). Email will be sent WITHOUT attachment.")

                    # Send the email
                    server.send_message(msg)
                    print(f"📧 Email sent to: {name} at {recipient_email}")
                    
                    # --- NEW: DELAY TO AVOID GOOGLE LOCKOUT ---
                    print("⏳ Pausing for 8 seconds to mimic human sending rate...\n")
                    time.sleep(8)
                
        print("🎉 All emails from the CSV have been processed successfully!")

    except smtplib.SMTPAuthenticationError:
        print("❌ Authentication Error: The App Password or Email in your .env file is incorrect.")
    except Exception as e:
        print(f"❌ An unexpected error occurred: {e}")

if __name__ == '__main__':
    send_csv_emails()